spring:
  application:
    name: EurekaServer

eureka:  
  instance: 
    appname: ${spring.application.name}
#    lease-renewal-interval-in-seconds: 30 #Eureka Client 가 여전히 활성 상태임을 나타내기 위해 Eureka Server 에 heartbeat 를 보내는 빈도를 나타내며 기본값은 30초이다. 즉, 30초 마다 한번씩 heartbeat 를 수신하게 된다. 가급적 기본값인 30초 사용을 권장한다.
#    lease-expiration-duration-in-seconds: 90 #Server 레지스트리에서 Client Instance 를 제거하기 전에 마지막 heartbeat 를 받은 후 서버가 대기하는 시간을 나타낸다.  이값은 앞서 말한 lease-renewal-interval-in-seconds 보다 커야한다. 이 값을 너무 길게 설정하면 레지스트리의 활성 상태가 설정값에 따라 달라지므로 이전에 설명한 lease-renewal-interval-in-seconds 의 분당 실제 heartbeat 계산의 정밀도에 영향을 주게 된다고 한다. 또한 너무 작게 설정하면 시스템이 일시적인 네트워크 결함을 견딜 수 없게 된다고 한다. 
  server:
    enable-self-preservation: true # 자기 보호 모드(네트워크 장애가 발생하여도 서비스 해제를 방지하는 모드) 단일구성 개발시 비활성화
  client:
    register-with-eureka: true # 유레카 서비스에 미등록 (이중화 복제본일때만 서버 자체도 등록한다.) -> gateway 통과를 위해 개발계에서도 등록으로 한다.   
    fetch-registry: true #레지스트리 정보를 로컬에 캐싱 한다.    
    
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
---
spring:
  config:
    activate:
      on-profile:
      - local1
      
server:
  port: 10000 # 유레카 서버가 수신 대기할 포트

eureka:
  instance:
    hostname: localhost1   
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/
      
---
spring:
  config:
    activate:
      on-profile:
      - local2
      
server:
  port: 10001 # 유레카 서버가 수신 대기할 포트

eureka:  
  instance:
    hostname: localhost2   
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/,http://localhost:10001/eureka/

---
spring:
  config:
    activate:
      on-profile:
      - prod1
      
server:
  port: 10000 # 유레카 서버가 수신 대기할 포트
    
eureka:
  instance:
    hostname: gm-cloud1 # 서버의 hosts 안에 등록되어 있어야 한다.
  client:
    service-url:
      defaultZone: http://gm-cloud1:10000/eureka/,http://gm-cloud2:10000/eureka/
      
---
spring:
  config:
    activate:
      on-profile:
      - prod2
      
server:
  port: 10000 # 유레카 서버가 수신 대기할 포트
    
eureka:
  instance:
    hostname: gm-cloud2 # 서버의 hosts 안에 등록되어 있어야 한다.
  client:
    service-url:
      defaultZone: http://gm-cloud1:10000/eureka/,http://gm-cloud2:10000/eureka/